[package]
name = "idlepaste"
version = "0.1.1"
authors = ["mz2212 <michaelpulliam1@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
select = "0.5"
url = "2.2"
